// <auto-generated />
using System;
using CodeFirstDatabaseManagementPratice.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstDatabaseManagementPratice.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(CodeFirstDatabaseManagementPraticeDbContext))]
    partial class CodeFirstDatabaseManagementPraticeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstDatabaseManagementPratice.Domain.Samples.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasComment("流水號");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt")
                        .HasComment("建立時間");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Name")
                        .HasComment("名稱");

                    b.Property<string>("NullableName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NullableName")
                        .HasComment("可Null名稱");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt")
                        .HasComment("更新時間");

                    b.HasKey("Id");

                    b.ToTable("Samples", null, t =>
                        {
                            t.HasComment("示範資料表");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 26, 7, 56, 45, 21, DateTimeKind.Utc).AddTicks(2012),
                            Name = "不可為Null欄位"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
